### ISSUE TITLE
Star map generation

### ISSUE THREAD

**Issue by kgilpin** [kgilpin/nova-flask#1]
Add a function to generate a random map of stars.

Implement this as a new, standalone function.

Parameters include:

* Number of stars to be created
* Radius of the universe

Assign star names and magnitude from a file `nova/stars.yml`, which contains this type of data:

```yaml
- name: Acamar
  mag: 3.24
- name: Achernar
  mag: 0.46
...
```
